fix header width & little current link changes
fe-nov23-DOMinationDynasty/product_catalog pull request #30
Opened 2024-02-20 18:58 UTC by Yur1yBubl1k

2024-02-21 12:01 UTC, artem8746 commented on src/components/BurgerMenu/BurgerMenu.tsx
replace <a> by <Link>, remove currentUrl and setCurrentUrl

2024-02-21 12:02 UTC, artem8746 commented on src/components/BurgerMenu/BurgerMenu.tsx
replace `ul` by `nav` and delete `li`

2024-02-21 12:08 UTC, artem8746 commented on src/components/BurgerMenu/BurgerMenu.tsx
> +              />}
make it spans, add classes(check in buttons.scss) and change it when it's active

2024-02-21 12:09 UTC, artem8746 commented on src/components/Header/Header.tsx
>                <li className="list_item">
replace it by `<nav>`  and remove `<li>`

2024-02-21 12:11 UTC, artem8746 commented on src/components/Header/Header.tsx
> +                  }}
```suggestion

```
remove, you don't need onClick, when you use `to` attribute

2024-02-21 12:14 UTC, artem8746 commented on src/components/Header/Header.tsx
> +              }
use spans, learn (button.scss - `&-favourite`, and change classNames when status changed)

2024-02-21 12:16 UTC, artem8746 requested changes
💦💦💦💦💨💨💨💨
Amazing, just make a few changes

2024-02-23 09:16 UTC, artem8746 commented
remove scroll when burger menu opened

2024-02-27 10:56 UTC, sasholk requested changes
good job!
but need to change namings `className` by BEM and also use nesting in scss

2024-02-27 10:56 UTC, sasholk commented on src/components/BurgerMenu/BurgerMenu.tsx
> +  // const [currentURL, setCurrentURL] = useState('');
delete

2024-02-27 10:56 UTC, sasholk commented on src/components/Header/Header.tsx
> +// }
delete

2024-02-27 10:56 UTC, sasholk commented on src/components/Header/Header.tsx
> +  // const filteredDevices = filterDevices(qw, sortField);
delete

2024-02-28 14:37 UTC, artem8746 approved these changes
ヾ(^▽^*)))

2024-02-28 19:11 UTC, merged