bread crumbs
fe-nov23-DOMinationDynasty/product_catalog pull request #35
Opened 2024-02-21 15:34 UTC by HeySleare

2024-02-21 19:13 UTC, artem8746 commented on src/components/BreadCrumbs/BreadCrumbs.tsx
> +      currentLink += `/${crumb}`;
move it to function, would be better to use const instead

2024-02-21 19:14 UTC, artem8746 commented on src/components/BreadCrumbs/BreadCrumbs.tsx
> +    });
move it to function and put to services, would be better to use const instead

2024-02-21 19:15 UTC, artem8746 requested changes
💦💦
( •_•)>⌐■-■

2024-02-22 17:12 UTC, sasholk approved these changes
🦆

2024-02-22 17:16 UTC, merged