add card without fonts
fe-nov23-DOMinationDynasty/product_catalog pull request #9
Opened 2024-02-16 14:19 UTC by artem8746

2024-02-16 14:28 UTC, artem8746 commented on src/components/CardPhone/CardPhone.tsx
> +        </div>
```suggestion
        <p className="card__param-pair">
          <span className="card__params-info">Screen</span>
          <span className="card__params-value">6.1” OLED</span>
        </p>
```
put <p> when it's completed thought

2024-02-16 14:28 UTC, artem8746 commented on src/components/CardPhone/CardPhone.tsx
> +        </div>
change everywhere

2024-02-16 14:29 UTC, artem8746 commented on src/components/CardPhone/CardPhone.tsx
> +        </a>
```suggestion
        <button href="#addToCart" className="card__buttons-add">
          Add to cart
        </button>
```

2024-02-16 14:30 UTC, artem8746 commented on src/components/CardPhone/CardPhone.tsx
> +        <a href="#favourite" className="card__buttons-favourite">
```suggestion
        <a href="#" className="card__buttons-favourite">
```

2024-02-16 14:33 UTC, artem8746 commented on src/components/CardPhone/cardphone.scss
> +  height: 506px;
```suggestion

```

2024-02-16 14:33 UTC, artem8746 commented on src/components/CardPhone/cardphone.scss
> +    height: 196px;
```suggestion

```

2024-02-16 14:35 UTC, artem8746 commented on src/components/CardPhone/cardphone.scss
> +    margin-top: 0;
```suggestion
    margin-block: 8px 0;
```

2024-02-16 14:37 UTC, artem8746 commented on src/components/CardPhone/cardphone.scss
> +}
```suggestion
  &__buttons {
    display: flex;
    gap: 8px;
    align-items: center;
    justify-content: space-between;

  &-add {
    display: flex;

    align-items: center;
    justify-content: center;

    width: 160px;
    height: 40px;

    text-decoration: none;
    font-weight: 700;
    font-size: 14px;
    background-color:#313237;
    color: white;

    transition: background-color 0.3s ease, color 0.3s ease;

    &:hover {
      background-color: lightgrey;
      color: black;
    }
  }
}
  }
```

2024-02-16 14:39 UTC, sasholk requested changes
need to rework broski🖖

2024-02-18 18:36 UTC, l0ad1nggg approved these changes
ok

2024-02-18 18:56 UTC, merged